version: '3.9'

services:
  cog:
    image: ghcr.io/0-5788719150923125/eve:latest
    command: nodemon --ext '*.py, *.yml, *.scm' --exec python3 src/main.py
    restart: 'always'
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    env_file:
      - .env